//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOURISM.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TOURISM.Web.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation.
        /// </summary>
        public static string _Accommodation {
            get {
                return ResourceManager.GetString("_Accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation.
        /// </summary>
        public static string _Accommodation_1 {
            get {
                return ResourceManager.GetString("_Accommodation_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodations.
        /// </summary>
        public static string _Accommodations {
            get {
                return ResourceManager.GetString("_Accommodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string _Activities {
            get {
                return ResourceManager.GetString("_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axiom.
        /// </summary>
        public static string _Axiom {
            get {
                return ResourceManager.GetString("_Axiom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach.
        /// </summary>
        public static string _Beach {
            get {
                return ResourceManager.GetString("_Beach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children Classes.
        /// </summary>
        public static string _ChildrenClasses {
            get {
                return ResourceManager.GetString("_ChildrenClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string _Class {
            get {
                return ResourceManager.GetString("_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string _CopyRight {
            get {
                return ResourceManager.GetString("_CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultural Areas.
        /// </summary>
        public static string _CulturalAreas {
            get {
                return ResourceManager.GetString("_CulturalAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string _Destination {
            get {
                return ResourceManager.GetString("_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinations.
        /// </summary>
        public static string _Destinations {
            get {
                return ResourceManager.GetString("_Destinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string _Destinations_1 {
            get {
                return ResourceManager.GetString("_Destinations_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string _Discover {
            get {
                return ResourceManager.GetString("_Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string _English {
            get {
                return ResourceManager.GetString("_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Page.
        /// </summary>
        public static string _ErrorPage {
            get {
                return ResourceManager.GetString("_ErrorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilities.
        /// </summary>
        public static string _Facilities {
            get {
                return ResourceManager.GetString("_Facilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Classes.
        /// </summary>
        public static string _GeneralClasses {
            get {
                return ResourceManager.GetString("_GeneralClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Knowledge.
        /// </summary>
        public static string _GeneralKnowledge {
            get {
                return ResourceManager.GetString("_GeneralKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Page tou are trying to access was not found. Please contact the admin at elvinjreyesv@outlok.com.
        /// </summary>
        public static string _Global_PageNoFound {
            get {
                return ResourceManager.GetString("_Global_PageNoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred processing your request. Please try again later, or contact the administrator at elvinjreyesv@outlok.com..
        /// </summary>
        public static string _Global_ServerError {
            get {
                return ResourceManager.GetString("_Global_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Code.
        /// </summary>
        public static string _Global_ServerError_ReferenceCode {
            get {
                return ResourceManager.GetString("_Global_ServerError_ReferenceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string _GoBack {
            get {
                return ResourceManager.GetString("_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string _Home {
            get {
                return ResourceManager.GetString("_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        public static string _Individual {
            get {
                return ResourceManager.GetString("_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individuals Relates.
        /// </summary>
        public static string _IndividualsRelated {
            get {
                return ResourceManager.GetString("_IndividualsRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Relations.
        /// </summary>
        public static string _InferredAttributes {
            get {
                return ResourceManager.GetString("_InferredAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Areas.
        /// </summary>
        public static string _NaturalAreas {
            get {
                return ResourceManager.GetString("_NaturalAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string _Next {
            get {
                return ResourceManager.GetString("_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found.
        /// </summary>
        public static string _Notfound {
            get {
                return ResourceManager.GetString("_Notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology.
        /// </summary>
        public static string _Ontology {
            get {
                return ResourceManager.GetString("_Ontology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General vision of the Ontology.
        /// </summary>
        public static string _OntologyGeneralVision {
            get {
                return ResourceManager.GetString("_OntologyGeneralVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string _Paper {
            get {
                return ResourceManager.GetString("_Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string _Prev {
            get {
                return ResourceManager.GetString("_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string _Property {
            get {
                return ResourceManager.GetString("_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string _RightsReserved {
            get {
                return ResourceManager.GetString("_RightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string _Rooms {
            get {
                return ResourceManager.GetString("_Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string _Search {
            get {
                return ResourceManager.GetString("_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination, accomodation, room.
        /// </summary>
        public static string _SearchPlaceholder {
            get {
                return ResourceManager.GetString("_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string _SeeDetails {
            get {
                return ResourceManager.GetString("_SeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string _Spanish {
            get {
                return ResourceManager.GetString("_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourism.
        /// </summary>
        public static string _Tourism {
            get {
                return ResourceManager.GetString("_Tourism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town And Cities.
        /// </summary>
        public static string _TownAndCities {
            get {
                return ResourceManager.GetString("_TownAndCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all Destinations.
        /// </summary>
        public static string _ViewAllDestinations {
            get {
                return ResourceManager.GetString("_ViewAllDestinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter Sport Areas.
        /// </summary>
        public static string _WinterSportAreas {
            get {
                return ResourceManager.GetString("_WinterSportAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation Group.
        /// </summary>
        public static string AccommodationGroups {
            get {
                return ResourceManager.GetString("AccommodationGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continent.
        /// </summary>
        public static string AccommodationsByContinents {
            get {
                return ResourceManager.GetString("AccommodationsByContinents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodations Under.
        /// </summary>
        public static string accommodationsUnder {
            get {
                return ResourceManager.GetString("accommodationsUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation Type.
        /// </summary>
        public static string AccommodationTypes {
            get {
                return ResourceManager.GetString("AccommodationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation Type.
        /// </summary>
        public static string AccType {
            get {
                return ResourceManager.GetString("AccType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Offered By.
        /// </summary>
        public static string actOfferedBy {
            get {
                return ResourceManager.GetString("actOfferedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation With Rooms.
        /// </summary>
        public static string actWithRoom {
            get {
                return ResourceManager.GetString("actWithRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amenities.
        /// </summary>
        public static string amenities {
            get {
                return ResourceManager.GetString("amenities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awards.
        /// </summary>
        public static string awards {
            get {
                return ResourceManager.GetString("awards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Beach {
            get {
                return ResourceManager.GetString("Beach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation Brand.
        /// </summary>
        public static string brandAccommodation {
            get {
                return ResourceManager.GetString("brandAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string brandCode {
            get {
                return ResourceManager.GetString("brandCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continent.
        /// </summary>
        public static string continent {
            get {
                return ResourceManager.GetString("continent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralKnowledge {
            get {
                return ResourceManager.GetString("GeneralKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilities.
        /// </summary>
        public static string hasFacility {
            get {
                return ResourceManager.GetString("hasFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        public static string hasRestaurant {
            get {
                return ResourceManager.GetString("hasRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string hasRoom {
            get {
                return ResourceManager.GetString("hasRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars.
        /// </summary>
        public static string hasStars {
            get {
                return ResourceManager.GetString("hasStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string HotelRating {
            get {
                return ResourceManager.GetString("HotelRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string isLocated {
            get {
                return ResourceManager.GetString("isLocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Price.
        /// </summary>
        public static string maxPrice {
            get {
                return ResourceManager.GetString("maxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Plan.
        /// </summary>
        public static string MealPlan {
            get {
                return ResourceManager.GetString("MealPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Price.
        /// </summary>
        public static string minPrice {
            get {
                return ResourceManager.GetString("minPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string NaturalAreas {
            get {
                return ResourceManager.GetString("NaturalAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms Qty.
        /// </summary>
        public static string numberRooms {
            get {
                return ResourceManager.GetString("numberRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string offer {
            get {
                return ResourceManager.GetString("offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Activity.
        /// </summary>
        public static string offerActivity {
            get {
                return ResourceManager.GetString("offerActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offered By.
        /// </summary>
        public static string offeredBy {
            get {
                return ResourceManager.GetString("offeredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Adults.
        /// </summary>
        public static string onlyAdults {
            get {
                return ResourceManager.GetString("onlyAdults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Facilities.
        /// </summary>
        public static string roomFacility {
            get {
                return ResourceManager.GetString("roomFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string underBrand {
            get {
                return ResourceManager.GetString("underBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors.
        /// </summary>
        public static string visitors {
            get {
                return ResourceManager.GetString("visitors", resourceCulture);
            }
        }
    }
}
